local sourceInfo = debug.getinfo(1, "S").source
local script = sourceInfo:sub(1, 1) == "@" and sourceInfo:sub(2) or sourceInfo
local testsDirectory = script:match("^(.*)/[^/]+$") or "."
local path = testsDirectory .. "/../codex_math_preview_hotkey.lua"
local handle = assert(io.open(path, "rb"))
local source = handle:read("*a")
handle:close()

local forbidden = {
  "hs.pasteboard", "hs.eventtap", "setAttributeValue", "performAction",
  "hs.mouse", "selectMenuItem", "hs.http", "hs.urlevent", "openURL",
  "keyStroke", "keyStrokes", "newKeyEvent",
}
for _, token in ipairs(forbidden) do
  assert(not source:find(token, 1, true), "forbidden preview capability: " .. token)
end
assert(not source:match('["\']return["\']'), "Return key token is forbidden")
assert(not source:match('["\']enter["\']'), "Enter key token is forbidden")
assert(not source:find("http://", 1, true), "network URL is forbidden")
assert(not source:find("https://", 1, true), "network URL is forbidden")
assert(not source:find("templatePath", 1, true), "template path field is forbidden")
assert(not source:find("baseURL", 1, true), "base URL field is forbidden")
assert(not source:find("file://", 1, true), "file URL is forbidden")
assert(source:find("resolveAssetsDirectory", 1, true), "bound assets resolver is required")
assert(source:find('hs.configdir .. "/codex_math_preview_assets"', 1, true), "fixed config asset root is required")
assert(source:find('"preview-bundle.html"', 1, true), "self-contained bundle evidence is required")
assert(source:find("EXPECTED_PREVIEW_BUNDLE_SHA256", 1, true), "fixed bundle hash is required")
assert(source:find("hs.hash.SHA256(bundleBytes)", 1, true), "runtime bundle hash verification is required")
assert(source:find('"preview-template.html"', 1, true), "template deployment evidence is required")
assert(source:find('"preview.js"', 1, true), "script deployment evidence is required")
assert(source:find('"preview.css"', 1, true), "style deployment evidence is required")
assert(source:find('"vendor/katex/VERSION"', 1, true), "KaTeX version evidence is required")
assert(source:find('"vendor/katex/LICENSE"', 1, true), "KaTeX license evidence is required")
assert(source:find('attributeValue("AXValue")', 1, true), "AXValue must be read directly")
assert(source:find("policyCallback", 1, true), "policy callback is required")
assert(source:find("windowCallback", 1, true), "window focus callback is required")
assert(source:find("view:allowTextEntry(true)", 1, true), "native WebKit focus events must be enabled")
assert(not source:find("previewFocused", 1, true), "synthetic preview focus query is forbidden")
assert(not source:find("isPreviewHost", 1, true), "host activation must not imply preview focus")
assert(not source:find("hs.window.focusedWindow", 1, true), "global window focus query is forbidden")
assert(source:find('applicationsForBundleID("org.hammerspoon.Hammerspoon")', 1, true), "preview host activation is required")
assert(source:find('bundleID == "org.hammerspoon.Hammerspoon" and activePreview ~= nil', 1, true), "Control+Q must remain active only while preview is open")
assert(not source:find("previewWindow:focus()", 1, true), "blocking synchronous WebView focus is forbidden")
assert(source:find("focusArmTimer", 1, true), "generation-bound focus arm timer is required")
assert(source:find('CHROME_BUNDLE_ID = "com.google.Chrome"', 1, true), "Chrome hotkey scope is required")
assert(source:find('DEFAULT_MODIFIERS = { "ctrl" }', 1, true), "Control-only preview hotkey is required")
assert(source:find('DEFAULT_KEY = "q"', 1, true), "Control+Q preview hotkey is required")
assert(source:find("hs.screen.allScreens()", 1, true), "preview target must consider all screens")
assert(source:find("middleScreenFrame", 1, true), "preview must choose the middle screen")
assert(source:find('screen:name() == "Redmi 27 NU"', 1, true), "middle display anchor must be explicit")
assert(source:find("return view, desired", 1, true), "preview must retain computed target coordinates")
assert(source:find("hs.drawing.windowLevels.screenSaver", 1, true), "active preview must use topmost window level")
assert(source:find("bringToFront(true)", 1, true), "active preview must be above all windows")
assert(source:find("screenFrame.w * 0.28", 1, true), "preview should match the compact yellow region of the middle screen")
assert(source:find("screenFrame.h * 0.96", 1, true), "preview should use nearly the full middle-screen height")
assert(not source:find('attributeValue("AXURL")', 1, true), "page URL reads are forbidden")
assert(not source:find("AXChildren", 1, true), "AX tree scanning is forbidden")
assert(not source:find("allDescendant", 1, true), "AX descendant scanning is forbidden")
assert(source:find('role == "AXSecureTextField"', 1, true), "secure text fields must be rejected")
assert(source:find("chromeProtectionState", 1, true), "Chrome protection state must be tri-state")
assert(source:find("attributeNameSet", 1, true), "Chrome must distinguish absent AX attributes")
assert(source:find("readListedAttribute", 1, true), "AX protection read failures must be distinguishable")
assert(source:find("codex-math-preview://close", 1, true), "local close route is required")
assert(source:find("createWarmPreview", 1, true), "empty warm preview creation is required")
assert(source:find("local warmFrames = {}", 1, true), "warm preview frame registry is required")
assert(source:find("view:allowTextEntry(false)", 1, true), "empty warm preview must reject keyboard entry")
assert(source:find("view:allowTextEntry(true)", 1, true), "consumed preview must restore focus callbacks")
assert(source:find("view:alpha(0)", 1, true), "empty warm preview must remain transparent")
assert(source:find("view:level(hs.drawing.windowLevels.desktop)", 1, true), "empty warm preview must stay below interactive windows")
assert(source:find("view:level(hs.drawing.windowLevels.screenSaver)", 1, true), "active preview must restore topmost window level")
assert(source:find("screenFrame.x - desired.w - 10000", 1, true), "empty warm preview must remain offscreen at final size")
assert(source:find("w = desired.w", 1, true), "warm preview must pre-layout at final width")
assert(source:find("view:alpha(1)", 1, true), "consumed warm preview must become visible only after render")
assert(source:find("renderPreview", 1, true), "one-shot warm render API is required")
assert(source:find('window.codexMathPreview.render(" .. jsonForHtml(json) .. ")', 1, true), "warm render must pass validated JSON directly")
assert(not source:find("hs.json.encode(json, false)", 1, true), "Hammerspoon cannot encode a JSON string twice")
assert(source:find("takeWarmPreview", 1, true), "ready warm preview must be consumed")
assert(not source:find("hideView", 1, true), "draft-bearing views must not be hidden for reuse")

return "PASS preview static read-only safety"
